name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: sonarscan-dotnet
        uses: highbyte/sonarscan-dotnet@v2.1.2
        with:
          sonarProjectKey: polterguy_magic.lambda.mime
          sonarProjectName:  magic.lambda.mime
          sonarOrganization: polterguy
          dotnetBuildArguments: ./magic.lambda.mime/magic.lambda.mime.csproj
          dotnetTestArguments: ./magic.lambda.mime.tests/magic.lambda.mime.tests.csproj --logger trx --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
          sonarBeginArguments: /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml" -d:sonar.cs.vstest.reportsPaths="**/*.trx"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}