name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: sonarscan-dotnet
        uses: highbyte/sonarscan-dotnet@v2.1.2
        with:
          sonarProjectKey: polterguy
          sonarProjectName:  magic.lambda.mime
          sonarOrganization: polterguy
          dotnetBuildArguments: ./magic.lambda.mime/magic.lambda.mime.csproj
          dotnetTestArguments: ./magic.lambda.mime.tests/magic.lambda.mime.tests.csproj
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}